### PR TITLE
fix: code copy functionality

### PR DESCRIPTION
**Pull request by henilp105**
fixes the bug  reported in #89.

CC: @certik @Shaikh-Ubaid

### CODE REVIEW

**Review by Shaikh-Ubaid — APPROVED** [review]
This looks good to me.

**Comment by Shaikh-Ubaid** [comment]
Yes, I have known this bug. I have been hoping to fix it for some long time. The fix you sent is very helpful. Thank you so much @henilp105! We appreciate it.

**Comment by Shaikh-Ubaid** [comment]
I merging this PR. I will closely follow the CI and ensure the changes work fine at https://dev.lfortran.org/.

**Comment by certik** [comment]
Thanks!

**Pull request merged**
