### PR TITLE
Update LFortran to 0.30.0

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
The preview site gives an error message:
```
code generation error: SubroutineCall: Function show_img_color not found


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.

Compilation Time: 28 ms
```

**Comment by Shaikh-Ubaid** [comment]
>The preview site gives an error message:

This seems to be fixed. Please note we need to do hard refersh (ctrl/cmd +shift + r) to reload the site.

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks good to me. Thank you for this.

**Comment by Shaikh-Ubaid** [comment]
I checked the deployed lfortran at `dev.lfortran.org`. All the examples seem to work.

**Comment by certik** [comment]
Perfect, it works! Thank you @Shaikh-Ubaid for fixing it.

**Pull request merged**
