### PR TITLE
CI: Fix failure for PRs from fork

### LINKED ISSUE #48: CI fails for Pull Requests from a fork
>@Shaikh-Ubaid do you know why the CI failed? I am trying to update to the latest LFortran.

It seems the `CI` failed to create a deployment comment. Ideally, it should not be attempting to create a deployment comment, since the `PR` is raised from a fork. At the moment, we can try pushing into the `origin` repository, so that create deployment comment could work and the `CI` passes.

_Originally posted by @Shaikh-Ubaid in https://github.com/lfortran/lcompilers_frontend/issues/45#issuecomment-1304403860_

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes #48

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
There is no attempt to create a deployment comment (which is desired as the PR is raised from a fork) and the CI passes. It seems to work. Please possibly review and please share feedback.

**Comment by Shaikh-Ubaid** [comment]
**doubt:** Since, there is no development/preview deployment taking place when the PR is raised from a fork. Please, could someone possibly share how we can view/test the changes? How do we know if the changes work and/or if the site builds?

**Comment by certik** [comment]
I don't know. I think for now we can just develop from the main repository. 

The workflow I am imagining is that anybody can send a PR, and the CI runs and builds a preview somehow.

**Comment by Shaikh-Ubaid** [comment]
>I think for now we can just develop from the main repository.
 
Dr. Ondrej, please, could you possibly share if we shall close this PR or continue and/or merge this.

The changes in this PR avoid the CI from failing when pull requests from a fork are created. The previewing of PRs raised from a fork is not yet supported.

**Review by certik — APPROVED** [review]
I think that's fine to merge.

**Comment by Shaikh-Ubaid** [comment]
Thank you for the approval.

**Pull request merged**
