### PR TITLE
Support lfortran.wasm and lfortran.js of different commits

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This `PR` adds support of using `lfortran.wasm` and `lfortran.js` of different `merge` commits of `lfortran` `master`.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
I am unsure if this would work. Up-till now the changes in this `PR` were working fine locally on my system. In the past half an hour, the requests for `lfortran.js` and `lfortran.wasm` started failing because of `CORS` errors.

The exact error is:
```bash
Access to fetch at 'https://ubaidshaikh.me/wasm_builds/commit1/lfortran.wasm' from origin 'http://localhost:8000' has been 
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response 
serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
I am still hoping that the changes in this `PR` could/would work when deployed as during deployment the domains for both the live site `dev.lfortran.org` and the `lfortran.wasm` storage site `lfortran.org/wasm_builds` are the same.

**Comment by certik** [comment]
I think the wasm file must be present in the same gh-pages branch as the rest of the site, and consequently available from dev.lfortran.org. I would not load it from elsewhere. See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for more information.

**Comment by certik** [comment]
To move forward, why not first implement just the latest wasm binary, copy it to gh-pages etc. Let's get it done, merged, etc.

After that, we can investigate how to support more versions.

**Comment by Shaikh-Ubaid** [comment]
I just setup a demo of this `PR` here https://www.ubaidshaikh.me/lcompilers_frontend/. (The view button of each commit is not working perfectly, but it can fixed later).

**Comment by Shaikh-Ubaid** [comment]
>I think the wasm file must be present in the same gh-pages branch as the rest of the site, and consequently available from dev.lfortran.org. I would not load it from elsewhere. See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for more information.

Got it.

>To move forward, why not first implement just the latest wasm binary, copy it to gh-pages etc. Let's get it done, merged, etc.
After that, we can investigate how to support more versions.

Got it. I am marking this `PR` as draft. I will continue this later.

**Comment by certik** [comment]
The demo looks very nice.

**Comment by Shaikh-Ubaid** [comment]
>I think the wasm file must be present in the same gh-pages branch as the rest of the site, and consequently available from dev.lfortran.org. I would not load it from elsewhere. See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for more information.

It seems `GitHub Pages` support `CORS` requests (reference: https://stackoverflow.com/a/26417091/11474769).

>At the moment, I am unsure if the changes in this PR would work. Up-till now the changes in this PR were working fine locally on my system. In the past half an hour, the requests for lfortran.js and lfortran.wasm started failing because of CORS (Cross-origin resource sharing) errors.

The changes worked initially but later stopped working, because, I guess later I was not using the right domain (I was using `https://ubaidshaikh.me`, today it started working when I used `https://www.ubaidshaikh.me`).

**Comment by certik** [comment]
It seems that CORS requires some setup and support, and even thought github might now support it, I think it is more robust if we can figure out a way for it to work from the same domain.

**Comment by Shaikh-Ubaid** [comment]
>It seems that CORS requires some setup and support, and even thought github might now support it, I think it is more robust if we can figure out a way for it to work from the same domain.

Got it. I am closing this for the moment.

**Pull request closed without merging**
