### PR TITLE
Rename master branch to main

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
@certik, please, could you possibly rename the `master` branch to `main`? This would hopefully make it in  `sync` with the default branch naming convention we follow at https://github.com/lfortran/lfortran

**Comment by certik** [comment]
Cool, I just renamed it. Can you make sure everything still works?

**Comment by Shaikh-Ubaid** [comment]
Can you make sure everything still works?

It seems the `CI` at `lfortran` fails when pushing. I will update it in some time.

**Comment by certik** [comment]
Thanks!

**Comment by Shaikh-Ubaid** [comment]
>>Can you make sure everything still works?

>It seems the `CI` at `lfortran` fails when pushing. I will update it in some time.

I submitted a `PR` here https://github.com/lfortran/lfortran/pull/619

**Pull request merged**
