### PR TITLE
Support cpu_time

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
Corresponding `PR` at `lfortran` https://github.com/lfortran/lfortran/pull/641

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Review by certik — APPROVED** [review]
Nice!

We should figure out how to test these. Until then this is good.

**Comment by Shaikh-Ubaid** [comment]
I added tests for it at https://github.com/lfortran/lfortran/pull/641.

Also, to test it at live site, I tried the following code at https://www.ubaidshaikh.me/lcompilers_frontend/commits/8f768cc70/
```fortran
program cpu_time_02_wasm
implicit none
integer :: i, j, k
real(8) :: t1, t2
interface
    subroutine cpu_time(t) bind(c)
        real(8), intent(out) :: t
    end subroutine
end interface
call cpu_time(t1)

do i = 1, 10000
    do j = 1, 10000
       k = i + j
        if (k == 10000) then
            print *, "i =", i, ", j =", j
        end if
    end do
end do
         
call cpu_time(t2)
print *, "Total time: ", t2-t1
end program
```
The time output is `Total time:  0.3039999008178711`. It seems to work.

**Comment by Shaikh-Ubaid** [comment]
We can also test the same above code at https://dev.lfortran.org/ 

(I realised this just now that to test `cpu_time` we might not need the latest `lfortran` build, since the changes made to support `cpu_time` were not in `lfortran` but on the `JavaScript` side. These `JavaScript` changes were submitted/updated to both the repositories, and I guess, therefore the `cpu_time` works at https://dev.lfortran.org/).

**Comment by certik** [comment]
Right. Yes, everything looks good.

I think we can use this `bind(c)` approach to implement the parts of the runtime library that cannot be done in pure Fortran.

**Pull request merged**
