### PR TITLE
Fix flicker and auto run

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lcompilers_frontend/issues/101

fixes https://github.com/lfortran/lcompilers_frontend/issues/99

fixes https://github.com/lfortran/lcompilers_frontend/issues/103

towards https://github.com/lfortran/lcompilers_frontend/issues/104

### CODE REVIEW

**Comment by certik** [comment]
Not sure what is going on:

Screen Shot 2023-09-01 at 1 56 08 PM

**Comment by Shaikh-Ubaid** [comment]
For every preview we have two build processes. One happens in this repository and pushes to the repository `pull_request_preview`. After the push, the CI at that repo (which is the default github-pages deploy provided by GitHub) is triggered. The CI at that repo seems to be executing currently which we can track here https://github.com/lfortran/pull_request_preview/actions (the first one from this list).

**Comment by certik** [comment]
Ah got it. It works!

Here is what I am getting

Screen Shot 2023-09-01 at 2 01 45 PM

**Comment by Shaikh-Ubaid** [comment]
It https://github.com/lfortran/lcompilers_frontend/pull/105#issuecomment-1703262476 should be fixed now.

**Comment by Shaikh-Ubaid** [comment]
I think this fixes `3` of the issues at https://github.com/lfortran/lcompilers_frontend/issues/104.

**Review by certik — APPROVED** [review]
I think this works!

Let's merge it, and we'll see how it goes. If I discover any further issues, I'll report them.

Thanks @Shaikh-Ubaid !

**Pull request merged**
