### PR TITLE
Update LFortran commit in build.sh

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This `PR` updates the `lfortran` commit to the latest commit.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback. 

Please also see: https://github.com/lfortran/lfortran/pull/1034, https://github.com/lfortran/wasm_builds/pull/4

**Comment by certik** [comment]
The preview works for me. I merged this, and let's hope it will work once updated!

**Comment by Shaikh-Ubaid** [comment]
It seems the examples [integration_tests/template_nested.f90](https://github.com/lfortran/lfortran/blob/main/integration_tests/template_nested.f90) and [integration_tests/template_travel.f9](https://github.com/lfortran/lfortran/blob/main/integration_tests/template_travel.f90) work at https://dev.lfortran.org/!

**Comment by certik** [comment]
@Shaikh-Ubaid it works! Thank you so much for fixing it!

**Pull request merged**
