### PR TITLE
Support runtime library

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
Corresponding `PR` at `lfortran`: https://github.com/lfortran/lfortran/pull/643

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Review by certik — APPROVED** [review]

**Comment by Shaikh-Ubaid** [comment]
We did not update the `latest_commit` to be used to download the `lfortran.wasm` and `lfortran.js`.Therefore, the site should still work after we merge this as it fetches the old (and working) `lfortran.js` and `lfortran.wasm`. We might get a `curl` error that `lfortran.data` is not found, but I guess that should/would be fine.

**Comment by Shaikh-Ubaid** [comment]
As this is approved, I am merging this.

**Comment by certik** [comment]
Right. It's good that we do the manual upgrade, now we can control what exactly gets installed.

**Pull request merged**
