### PR TITLE
Update lfortran commit sha

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This `PR` updates the `latest_commit` to current available latest_commit at https://github.com/lfortran/wasm_builds/blob/main/docs/dev/latest_commit. 

Since, this is the first time we are trying the `pull_request_preview` feature, this `PR` also fixes some of the issues discovered, related to the `CI` and/or `pull_request_preview` feature. 

PS: This `PR` is related to or in continuation of https://github.com/lfortran/lcompilers_frontend/pull/38.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
- The deployment preview is available at https://lfortran.github.io/pull_request_preview/.
- The original site is at https://dev.lfortran.org/
- This PR updates the default example to use `dp=kind(0.d0)` in place of `dp=8`. This is also reflected in the deployment preview.

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Review by certik — APPROVED** [review]
I think that looks good.

**Comment by Shaikh-Ubaid** [comment]
Thank you for the approval!

**Pull request merged**
