### PR TITLE
Simplify (speedup) Mandelbrot code

### PR DESCRIPTION
**Pull request by certik**
* Do not make an extra image array copy
* Remove some commented print statements

### CODE REVIEW

**Comment by certik** [comment]
I also formatted the code a little bit better.

**Comment by certik** [comment]
I noticed the CI does not run here (#15).

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks Great! Thank you!

**Comment by Shaikh-Ubaid** [comment]
Sorry for the delayed review.

**Pull request merged**
