### PR TITLE
Update LFortran

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
Awesome, the deployment works. However, the `kind` function doesn't work again:
```
semantic error: Module 'lfortran_intrinsic_kind' not declared in the current source and the modfile was not found
 --> input:2:59
  |
2 | integer, parameter :: Nx = 600, Ny = 450, n_max = 255, dp=kind(0.d0)
  |                                                           ^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```
I know we had this issue before. @Shaikh-Ubaid do you remember how to fix it?

**Comment by Shaikh-Ubaid** [comment]
>I know we had this issue before. @Shaikh-Ubaid do you remember how to fix it?

I am looking into it.

**Comment by Shaikh-Ubaid** [comment]
I think, I figured the solution. I will be submitting the change to `lfortran` soon.

**Comment by certik** [comment]
Awesome, perfect!

**Comment by Shaikh-Ubaid** [comment]
I submitted it here https://github.com/lfortran/lfortran/pull/990. I think we should review/merge/complete it and then update the `lfortran` commit.

**Comment by certik** [comment]
I think it works. Thanks @Shaikh-Ubaid for fixing it! I merged it. I am trying to run the template example (https://github.com/lfortran/lfortran/issues/989) it now gets all the way to ASR, but fails in ASR->WASM due to https://github.com/lfortran/lfortran/issues/988.

**Comment by Shaikh-Ubaid** [comment]
>I am trying to run the template example (https://github.com/lfortran/lfortran/issues/989) it now gets all the way to ASR, but fails in ASR->WASM due to https://github.com/lfortran/lfortran/issues/988.

Got it. On it.

**Pull request merged**
