### PR TITLE
Add example template_array_04

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready.

**Comment by certik** [comment]
It does not load for me, so let's wait with merging.

**Comment by Shaikh-Ubaid** [comment]
>It does not load for me, so let's wait with merging.

It seems to load for me. Please, could you try refreshing using `ctrl/cmd` + `shift` + `r`?

**Review by certik — APPROVED** [review]
It works for me now, so I am approving it. After you merge, watch it to make sure everything works.

**Pull request merged**
