### PR TITLE
Update the code to use row-major order

### PR DESCRIPTION
**Pull request by certik**
Requires https://github.com/lfortran/lfortran/pull/621.

### CODE REVIEW

**Comment by certik** [comment]
I made a few mistakes of course, but I tested it locally with a locally built `lfortarn.wasm` and it seems to work now.

**Comment by certik** [comment]
We have to wait until https://github.com/lfortran/wasm_builds updates with the new `lfortran.wasm`. Currently at https://github.com/lfortran/wasm_builds/commit/5e0caf9ba150bba6dcf397cd2d4efe36d93ddef5. Then we can merge this PR that will use that new `lfortran.wasm` and it should work with the changes in this PR.

**Comment by certik** [comment]
I think it updated. So I am going to merge this PR and let's see.

**Comment by Shaikh-Ubaid** [comment]
I just tested the latest `lfortran.wasm` on my system. The output does not seem to be as expected.
image

**Comment by certik** [comment]
Can you retest? It seems to work now.

**Comment by Shaikh-Ubaid** [comment]
>Can you retest? It seems to work now.

It seems to work
image

image

**Pull request merged**
